"""驱动协议。"""

from __future__ import annotations

from typing import Any, Protocol


class Tx(Protocol):
    def commit(self) -> None: ...
    def rollback(self) -> None: ...


class Driver(Protocol):
    def dialect(self) -> str: ...
    def exec(self, stmt: Any, params: dict | None = None) -> Any: ...
    def query(self, stmt: Any, params: dict | None = None) -> Any: ...
    def tx(self) -> Tx: ...
